# Generated by Django 3.2 on 2022-03-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_create_task_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
